---
title: "Project Proposal"
output: html_notebook
---


# Project Proposal


## Section 1. Introduction

College students often have lots of assignments to do, early classes, and many other activities that occupy their time. All of these factors influence their sleep and therefore their mental health, physical health, and academic performance. We strive to discover how these factors influence students through the following research question:


   - What is the distribution of sleep quality among college students and are there any significant factors affecting sleep quality (Drinking, stress, depression, anxiety, etc.) and is there a correlation between the number hrs slept and cognitive function scores on the skill test?
  

Let's explore and answer this question.

Our project investigates 254 students who were surveyed for this sleep study including characteristics such as the quantity of early classes taken, GPA, quantity and quality of sleep, depression score, anxiety score, stress score, etc. This is our project for Foundations of Data Analytics (Fall 2023) class.

## Section 2. Data Analysis Plan
   
  - What is the distribution of sleep quality among college students and are there any significant factors affecting sleep quality (Drinking, stress, depression, anxiety, etc.) and is there a correlation between the number hrs slept and cognitive function scores on the skill test?
  
  
    - How does a student's alcohol use influence their sleep quality?
    
    - How does a student's mental health influence their sleep quality?
    
    - How does a student's sleep tendencies influence their sleep quality?
    
    - How does a student's happiness influence their sleep quality?
    
    - How does the number of early classes influence students' sleep quality?
    
    - What are the defining characteristics of the distributions?
    
    - Do certain groups have better academic performance or fewer missed classes compared to others?
    
    - Do any clusters exhibit particularly extreme values in certain variables (Ex. very high stress, very low cognitive function, etc.)?


## Section 3. Data

This dataset was obtained from the `SleepStudy` dataset provided through Professor Sanchez-Arias' github datasets repository. 


|Variable               |Description|
|:----------------------|:---------------------------------------------------------|
|Gender                 | 1 = male, 0 = female                                     |
|ClassYear              |Year in school, 1 = first year, ..., 4 = senior           |
|LarkOwl                |Early riser of night owl? Lark, Neither, or Owl           |
|NumEarlyClass          |Number of classes per week before 9am                     |
|EarlyClass             |Indicator for any early classes                           |
|GPA                    |Grade point average (0-4 scale)                           |
|ClassesMissed          |Number of classes missed in a semester                    |
|CognitionZscore        |Z-score on a test of cognitive skills                     |
|PoorSleepQuality       |Measure of sleep quality (higher values are poorer sleep) |
|DepressionScore        |Measure of degree of depression                           |
|AnxietyScore           |Measure of amount of anxiety                              |
|StressScore            |Measure amount of stress                                  |
|DepressionStatus       |Coded depression score: normal, moderate, or severe       |
|AnxietyStatus          |Coded anxiety score: normal, moderate, or severe          |
|Stress                 |Coded stress score: normal or high                        |
|DASScore               |Combined score for depression, anxiety and stress         |
|Happiness              |Measure of degree of happiness                            |
|AlcoholUse             |Self-reported: Abstain, Light, Moderate, or Heavy         |
|Drinks                 |Number of alcoholic drinks per week                       |
|WeekdayBed             |Average weekday bedtime (24.0 = midnight)                 |
|WeekdayRise            |Average weekday rise time (8.0 = 8am)                     |
|WeekdaySleep           |Average hours of sleep on weekdays                        |
|WeekendBed             |Average weekend bedtime (24.0 = midnight)                 |
|WeekendRise            |Average weekend rise time (8.0 = 8am)                     |
|WeekendSleep           |Average weekend bedtime (24.0 = midnight)                 |
|AverageSleep           |Average hours of sleep for all days                       |
|AllNighter             |Had an all-nighter this semester? 1 = yes, 0 = no         |
